---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[neo4jenv::default]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.10.5"}]
      - ["forwarded_port", {guest: 7474, host: 7474, auto_correct: true}]
      synced_folders: [
        ["data", "/tmp/data"]
      ]
    attributes:
      java:
        jdk_version: 7
