Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "memcache" do |memcache_config|
  	memcache_config.vm.hostname = "memcache"
  	memcache_config.vm.network "private_network", ip: "192.168.10.5"
  	memcache_config.vm.network "forwarded_port", guest: 11211, host: 11211

    memcache_config.vm.provision :chef_zero do |chef|      
      chef.add_recipe "memcached::default"
    end
  end
end
