---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[rabbitenv::default]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.10.5"}]
      - ["forwarded_port", {guest: 5672, host: 5672, auto_correct: true}]
      - ["forwarded_port", {guest: 15672, host: 15672, auto_correct: true}]
    attributes:
      cluster: false
      erlang_cookie: '123456789asdfghjkl'
