Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "rabbitmq" do |rabbitmq_config|
  	rabbitmq_config.vm.hostname = "rabbitmq"
  	rabbitmq_config.vm.network "private_network", ip: "192.168.10.5"
  	rabbitmq_config.vm.network "forwarded_port", guest: 5672, host: 5672
    rabbitmq_config.vm.network "forwarded_port", guest: 15672, host: 15672

    rabbitmq_config.vm.provision :chef_zero do |chef|
      chef.add_recipe "rabbitenv::default"
    end
  end
end
