---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: master
    run_list:
      - recipe[apt::default]
      - recipe[mongodb::default]
      - recipe[mongodbenv::default]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.10.5"}]
      - ["forwarded_port", {guest: 27017, host: 27017, auto_correct: true}]
      synced_folders: [
        ["data", "/tmp/data"]
      ]
    attributes:
      mongodb:
        config:
          port: 27017
          smallfiles: true
          auth: false
