---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[nodejs::default]
      - recipe[nodejsenv::default]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.10.5"}]
      - ["forwarded_port", {guest: 3000, host: 3000, auto_correct: true}]
      synced_folders: [
        ["app", "/tmp/app"]
      ]
    attributes:
      nodejs:
          version: '4.0.0'
