Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "nodejs" do |nodejs_config|
  	nodejs_config.vm.hostname = "nodejs"
  	nodejs_config.vm.network "private_network", ip: "192.168.10.5"
  	nodejs_config.vm.network "forwarded_port", guest: 3000, host: 3000
    nodejs_config.vm.synced_folder "app", "/tmp/app"

    nodejs_config.vm.provision :chef_zero do |chef|      
      chef.add_recipe "git::default"
      chef.add_recipe "nodejs::default"
      chef.add_recipe "nodejsenv::default"
    end
  end
end
