Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define "storage" do |storage_config|
  	storage_config.vm.hostname = "storage"
  	storage_config.vm.network "private_network", ip: "192.168.10.5"
  	storage_config.vm.network "forwarded_port", guest: 3306, host: 3306

    storage_config.vm.provision :chef_zero do |chef|
      chef.add_recipe "mysqlenv::default"
    end
  end
end
