---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[apache2::default]
      - recipe[apacheenv::default]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.10.5"}]
      - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
      - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      synced_folders: [
        ["www", "/tmp/www"]
      ]
    attributes:
      apache:
        default_site_enabled: false
        docroot_dir: "/tmp/www"
